# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2025 Casper Andersson <casper.casan@gmail.com>
name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build x86
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Debug workspace
        run: |
          echo "src contents:"
          ls -l
          ls -l src
      - name: Build
        run: |
          make
      # - name: Test
      #   run: |
      #     sudo make pipeline_test
          # Use sudo and a specific pipeline_test command since in
          # Ubuntu 24.04 you can't run `unshare` when unprivilegied.
  build-aarch64:
    name: Build aarch64
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Installing dependencies
        run: |
          sudo apt install gcc-aarch64-linux-gnu
      - name: Build
        run: |
          make CC=/usr/bin/aarch64-linux-gnu-gcc
  build-arm:
    name: Build arm
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Installing dependencies
        run: |
          sudo apt install gcc-arm-linux-gnueabi
      - name: Build
        run: |
          make CC=/usr/bin/arm-linux-gnueabi-gcc

